// Shared course data for the AI Course Matchmaker quiz (index.html) and the course table (courses.html)
// ------------------------- Course data (from the AI Courses Masterlist, Aug 2026) -------------------------
// level: 1 beginner · 1.5 beg–int · 2 intermediate · 3 advanced
// cost: rough single number (USD) for filtering; costLabel carries the nuance
// format: self | live | exam   ·   cred: proctored | cert | badge
const COURSES = [
  {name:"AI Fluency: Framework & Foundations", provider:"Anthropic Academy", cat:"General", level:1, cost:0, costLabel:"Free", effort:4, timeLabel:"~4 hrs", format:"self", cred:"cert", vendor:"anthropic", topics:["prompting","fundamentals"], url:"https://academy.claude.com/", note:"Official Anthropic completion certificate; the 4D framework for working with AI."},
  {name:"Claude Certified Associate — Foundations", provider:"Anthropic", cat:"General", level:1.5, cost:99, costLabel:"$99 exam", effort:15, timeLabel:"120-min exam + prep", format:"exam", cred:"proctored", vendor:"anthropic", topics:["fundamentals","prompting"], url:"https://academy.claude.com/", note:"The non-developer Claude credential. Valid 12 months.", partner:true},
  {name:"Google AI Essentials", provider:"Google / Coursera", cat:"General", level:1, cost:49, costLabel:"~$49", effort:10, timeLabel:"~10 hrs", format:"self", cred:"cert", vendor:"google", topics:["fundamentals","prompting"], url:"https://grow.google/ai-essentials/", note:"The most widely recognized entry-level AI credential."},
  {name:"Google Prompting Essentials", provider:"Google / Coursera", cat:"General", level:1, cost:49, costLabel:"~$49", effort:8, timeLabel:"~8 hrs", format:"self", cred:"cert", vendor:"google", topics:["prompting"], url:"https://www.coursera.org/specializations/prompting-essentials-google", note:"Practical prompting frameworks for everyday work."},
  {name:"Microsoft Azure AI Fundamentals (AI-900)", provider:"Microsoft", cat:"General", level:1, cost:99, costLabel:"$99 exam", effort:12, timeLabel:"45-min exam + prep", format:"exam", cred:"proctored", vendor:"microsoft", topics:["fundamentals"], url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/", note:"AI & GenAI concepts, no coding. Free prep on Microsoft Learn."},
  {name:"AWS Certified AI Practitioner (AIF-C01)", provider:"AWS", cat:"General", level:1, cost:100, costLabel:"$100 exam", effort:15, timeLabel:"90-min exam + prep", format:"exam", cred:"proctored", vendor:"aws", topics:["fundamentals"], url:"https://aws.amazon.com/certification/certified-ai-practitioner/", note:"Foundational AI/ML/GenAI concepts; suits non-engineers too."},
  {name:"Google Cloud Generative AI Leader", provider:"Google Cloud", cat:"General", level:1, cost:99, costLabel:"$99 exam", effort:12, timeLabel:"90-min exam + prep", format:"exam", cred:"proctored", vendor:"google", topics:["strategy","fundamentals"], url:"https://cloud.google.com/learn/certification/generative-ai-leader", note:"Business-level GenAI certification; valid 3 years."},
  {name:"Career Essentials in Generative AI", provider:"Microsoft × LinkedIn", cat:"General", level:1, cost:0, costLabel:"Free", effort:5, timeLabel:"~5 hrs", format:"self", cred:"cert", vendor:"microsoft", topics:["fundamentals"], url:"https://www.linkedin.com/learning/paths/career-essentials-in-generative-ai-by-microsoft-and-linkedin", note:"Quick free path; certificate shows on your LinkedIn profile."},
  {name:"OpenAI Certifications — AI Foundations", provider:"OpenAI Academy", cat:"General", level:1, cost:0, costLabel:"Free (pilot)", effort:5, timeLabel:"Self-paced", format:"self", cred:"badge", vendor:"other", topics:["fundamentals"], url:"https://academy.openai.com/", note:"Pilot-gated today; wider rollout planned through 2026."},

  {name:"NN/g UX Certification — AI Specialty", provider:"Nielsen Norman Group", cat:"Design", level:2, cost:6000, costLabel:"≈$1,200 × 5 courses", effort:40, timeLabel:"5 live courses + exams", format:"live", cred:"proctored", vendor:"other", topics:["design","research","strategy"], url:"https://www.nngroup.com/ux-certification/specialties/", note:"The most respected credential in UX — the AI specialty appears on your NN/g certificate."},
  {name:"AI for Designers", provider:"Interaction Design Foundation", cat:"Design", level:1.5, cost:349, costLabel:"≈$349/yr membership", effort:18, timeLabel:"~5 weeks", format:"self", cred:"cert", vendor:"other", topics:["design","research"], url:"https://www.interaction-design.org/courses/ai-for-designers", note:"How AI changes research, ideation, prototyping, and testing."},
  {name:"Certificate in AI Fundamentals for UX", provider:"UX Design Institute", cat:"Design", level:1, cost:500, costLabel:"See site", effort:10, timeLabel:"3 weeks, 3 live masterclasses", format:"live", cred:"cert", vendor:"other", topics:["design","prompting"], url:"https://www.uxdesigninstitute.com/courses/ai-fundamentals-for-ux", note:"AI foundations built for UX people; no AI experience needed."},
  {name:"AI Product Design Certification", provider:"Designlab", cat:"Design", level:2, cost:2195, costLabel:"$2,195–$2,695", effort:150, timeLabel:"~12 months part-time", format:"live", cred:"cert", vendor:"other", topics:["design"], url:"https://designlab.com/", note:"Mentor-led program with a portfolio capstone; courses also à la carte (~$799)."},
  {name:"UI/UX Design for AI Products", provider:"Stanford Online", cat:"Design", level:2, cost:2950, costLabel:"$2,950", effort:50, timeLabel:"8-week cohort", format:"live", cred:"cert", vendor:"other", topics:["design","strategy"], url:"https://online.stanford.edu/courses/xgal0001-uiux-design-ai-products", note:"Stanford Certificate of Achievement; designing AI-native experiences."},
  {name:"Uxcel AI courses", provider:"Uxcel", cat:"Design", level:1, cost:150, costLabel:"Subscription", effort:10, timeLabel:"Bite-size lessons", format:"self", cred:"cert", vendor:"other", topics:["design"], url:"https://uxcel.com/courses/ai-in-ux-ui-design", note:"Lightweight continuous learning; a good complement to a bigger credential."},
  {name:"AI for Product Designers", provider:"Maven (Xinran Ma)", cat:"Design", level:2, cost:1300, costLabel:"$1,300", effort:20, timeLabel:"2-week live intensive", format:"live", cred:"cert", vendor:"other", topics:["design","prompting"], url:"https://maven.com/", note:"Hands-on AI workflows for product designers."},

  {name:"Claude Certified Developer — Foundations", provider:"Anthropic", cat:"Development", level:2, cost:125, costLabel:"$125 exam", effort:20, timeLabel:"120-min exam + prep", format:"exam", cred:"proctored", vendor:"anthropic", topics:["agents","coding"], url:"https://academy.claude.com/", note:"The Anthropic API: tool use, MCP, agents. Valid 12 months.", partner:true},
  {name:"Claude Certified Architect — Foundations", provider:"Anthropic", cat:"Development", level:3, cost:125, costLabel:"$125 exam", effort:25, timeLabel:"120-min exam + prep", format:"exam", cred:"proctored", vendor:"anthropic", topics:["agents"], url:"https://academy.claude.com/", note:"Scenario-based exam on designing Claude-powered systems at scale.", partner:true},
  {name:"Claude Certified Architect — Professional", provider:"Anthropic", cat:"Development", level:3, cost:175, costLabel:"$175 exam", effort:30, timeLabel:"120-min exam + prep", format:"exam", cred:"proctored", vendor:"anthropic", topics:["agents"], url:"https://academy.claude.com/", note:"Top-tier Anthropic credential.", partner:true},
  {name:"Anthropic Academy developer courses", provider:"Anthropic Academy", cat:"Development", level:1.5, cost:0, costLabel:"Free", effort:12, timeLabel:"Self-paced, a few hrs each", format:"self", cred:"cert", vendor:"anthropic", topics:["agents","coding","prompting"], url:"https://academy.claude.com/", note:"Claude with the API · MCP · Claude Code in Action — the intended prep for the Anthropic exams."},
  {name:"GitHub Copilot (GH-300)", provider:"GitHub / Microsoft", cat:"Development", level:2, cost:99, costLabel:"$99 exam", effort:15, timeLabel:"~100-min exam + prep", format:"exam", cred:"proctored", vendor:"microsoft", topics:["coding"], url:"https://learn.microsoft.com/en-us/credentials/certifications/github-copilot/", note:"AI-assisted development, prompt craft, responsible use."},
  {name:"Microsoft Azure AI Engineer Associate (AI-102)", provider:"Microsoft", cat:"Development", level:2, cost:165, costLabel:"$165 exam", effort:40, timeLabel:"~100-min exam + prep", format:"exam", cred:"proctored", vendor:"microsoft", topics:["rag","agents"], url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-engineer/", note:"GenAI solutions on Azure AI Foundry / Azure OpenAI, incl. RAG."},
  {name:"AWS Certified ML Engineer — Associate", provider:"AWS", cat:"Development", level:2, cost:150, costLabel:"$150 exam", effort:50, timeLabel:"130-min exam + prep", format:"exam", cred:"proctored", vendor:"aws", topics:["ml"], url:"https://aws.amazon.com/certification/", note:"ML engineering on AWS (SageMaker, MLOps)."},
  {name:"AWS Certified Generative AI Developer — Professional", provider:"AWS", cat:"Development", level:3, cost:300, costLabel:"$300 exam", effort:60, timeLabel:"180-min exam + prep", format:"exam", cred:"proctored", vendor:"aws", topics:["rag","agents"], url:"https://aws.amazon.com/certification/", note:"New pro-level GenAI cert: Bedrock, RAG, agentic architectures."},
  {name:"Google Cloud Professional ML Engineer", provider:"Google Cloud", cat:"Development", level:3, cost:200, costLabel:"$200 exam", effort:60, timeLabel:"2-hr exam + prep", format:"exam", cred:"proctored", vendor:"google", topics:["ml"], url:"https://cloud.google.com/learn/certification/machine-learning-engineer", note:"ML systems on Google Cloud, incl. GenAI on Vertex AI."},
  {name:"Databricks Generative AI Engineer Associate", provider:"Databricks", cat:"Development", level:2, cost:200, costLabel:"$200 exam", effort:30, timeLabel:"90-min exam + prep", format:"exam", cred:"proctored", vendor:"other", topics:["rag","ml"], url:"https://www.databricks.com/learn/certification/genai-engineer-associate", note:"LLM apps, RAG, and evaluation on Databricks."},
  {name:"NVIDIA Certified Associate: Generative AI & LLMs", provider:"NVIDIA", cat:"Development", level:2, cost:135, costLabel:"~$135 exam", effort:20, timeLabel:"~1-hr exam + prep", format:"exam", cred:"proctored", vendor:"other", topics:["ml","fundamentals"], url:"https://www.nvidia.com/en-us/learn/certification/generative-ai-llm-associate/", note:"LLM fundamentals and the NVIDIA stack."},
  {name:"DeepLearning.AI short courses", provider:"DeepLearning.AI / Coursera", cat:"Development", level:1, cost:0, costLabel:"Free–$49/mo", effort:2, timeLabel:"1–2 hrs each", format:"self", cred:"cert", vendor:"other", topics:["agents","rag","prompting","ml"], url:"https://www.deeplearning.ai/courses/", note:"Agents, RAG, prompting; specializations carry certificates."},
  {name:"Hugging Face Agents Course", provider:"Hugging Face", cat:"Development", level:2, cost:0, costLabel:"Free", effort:25, timeLabel:"Self-paced", format:"self", cred:"cert", vendor:"other", topics:["agents","coding"], url:"https://huggingface.co/learn", note:"Hands-on agent building with a completion certificate."},

  {name:"AI Product Management Specialization", provider:"Duke / Coursera", cat:"Product & Leadership", level:1.5, cost:98, costLabel:"~$49/mo (≈2 months)", effort:40, timeLabel:"~2–3 months part-time", format:"self", cred:"cert", vendor:"other", topics:["strategy"], url:"https://www.coursera.org/specializations/ai-product-management-duke", note:"ML for PMs, the AI product lifecycle, and human factors."},
  {name:"AI Product Strategy", provider:"Nielsen Norman Group", cat:"Product & Leadership", level:2, cost:1200, costLabel:"≈$1,200", effort:8, timeLabel:"1-day live course", format:"live", cred:"cert", vendor:"other", topics:["strategy","design"], url:"https://www.nngroup.com/courses/", note:"Counts toward the NN/g AI Specialty."},
  {name:"AI for Business Specialization", provider:"Wharton / Coursera", cat:"Product & Leadership", level:1, cost:98, costLabel:"~$49/mo (≈2 months)", effort:30, timeLabel:"~2 months", format:"self", cred:"cert", vendor:"other", topics:["strategy"], url:"https://www.coursera.org/specializations/ai-for-business-wharton", note:"AI strategy, data, and ethics for business leaders."},
  {name:"Designing and Building AI Products and Services", provider:"MIT xPRO", cat:"Product & Leadership", level:2, cost:3000, costLabel:"~$3K+", effort:40, timeLabel:"~8 weeks, cohort", format:"live", cred:"cert", vendor:"other", topics:["strategy"], url:"https://xpro.mit.edu/", note:"Executive-education option for product leaders."},
];
